### ISSUE TITLE
Order of NPC AI Packages

### ISSUE THREAD

**Issue by ghost** [Excinerus/AI-Overhaul-Patcher#10]
I noticed that AI packages added by mods like Cutting Room Floor or Opulent Thieves Guild are forwarded, but then appear in the Packages (aligned) section in a different order. To my understanding packages will be used in order moving down the list until conditions are met, so this will makes those packages less likely to execute I think. Shouldn't the packages be forwarded in the same order? Specially when no AI Overhaul packages are added?

Here is a screenshot of what I'm talking about: https://imgur.com/GlPApwn

**Comment by Excinerus** [comment]
Yea it's an issue I've been looking into, the current behavior is the safest for now,  AIO modifies vanilla packages, some mods add disruptive packages that if set high on the list will not allow others to trigger, like CRF's vignar ending up sandboxing in dragons reach all day .

manual tweaking is necessary here, though package sorting still indeed needs some work.

**Comment by ghost** [comment]
It seems to be a good idea to have the other packages load after the AI Overhaul packages then, so they only execute if no AI Overhaul packages are executed. However I saw that for example ScoutsManyMarches doesn't have any AI Overhaul packages, but the CRF package is re-ordered to load after the default packages, seems like that shouldn't be happening. If No AI Overhaul packages are found I think the patcher should leave the packages alone.
