### ISSUE TITLE
v035.1 Mutagen patcher code giving a blocking error

### ISSUE THREAD

**Issue by seancojr** [Excinerus/AI-Overhaul-Patcher#13]
Synthesis reports an update is available for the patcher code but applying it gives the following error.

`Utilities\ExLoadOrderUtilities.cs(30,138): error CS0246: The type or namespace name 'IMajorRecordCommonGetter' could not be found (are you missing a using directive or an assembly reference?)
Utilities\ExLoadOrderUtilities.cs(30,138): error CS0246: The type or namespace name 'IMajorRecordCommonGetter' could not be found (are you missing a using directive or an assembly reference?)`

If I set the config to use versioning from the last successful run (01/05/2022), I can run the patcher with no error.

Synthesis version: 0.20.3
Mutagen version: 0.33.2

**Comment by Excinerus** [comment]
Fixed in [1518c66](https://github.com/Excinerus/AI-Overhaul-Patcher/commit/1518c6676e1e282d73f9985348d2765ffca07ad6) Thanks to Nogg :D
