### ISSUE TITLE
Deprecated function in new Synthesis UI

### ISSUE THREAD

**Issue by Glanzer-modder** [Excinerus/AI-Overhaul-Patcher#16]
Synthesis UI was just upgraded today and it looks like your patcher is using a deprecated function (see below).

Utilities\ExLoadOrderUtilities.cs(34,36): error CS1061: 'ILoadOrder<IModListing<ISkyrimModGetter>>' does not contain a definition for 'HasMod'

**Comment by dystopiat** [comment]
Confirming. I get the same error.

**Comment by KebunteL** [comment]
Same Problem.
New Synthesis Version Cause this Error and Blocking Error Message.

Utilities\ExLoadOrderUtilities.cs(34,36): error CS1061: 'ILoadOrder<IModListing<ISkyrimModGetter>>' does not contain a definition for 'HasMod' and no accessible extension method 'HasMod' accepting a first argument of type 'ILoadOrder<IModListing<ISkyrimModGetter>>' could be found (are you missing a using directive or an assembly reference?)
Utilities\ExLoadOrderUtilities.cs(34,36): error CS1061: 'ILoadOrder<IModListing<ISkyrimModGetter>>' does not contain a definition for 'HasMod' and no accessible extension method 'HasMod' accepting a first argument of type 'ILoadOrder<IModListing<ISkyrimModGetter>>' could be found (are you missing a using directive or an assembly reference?)

**Comment by Excinerus** [comment]
Updated in [dde1a4c](https://github.com/Excinerus/AI-Overhaul-Patcher/commit/dde1a4c504e40ab9109f32d503d35503e4c8b581)
