### ISSUE TITLE
Blocking Error: Utilities\ExLoadOrderUtilities.cs(34,36): error CS1061

### ISSUE THREAD

**Issue by ghyujkilop** [Excinerus/AI-Overhaul-Patcher#17]
Utilities\ExLoadOrderUtilities.cs(34,36): error CS1061: 'ILoadOrder<IModListing<ISkyrimModGetter>>' does not contain a definition for 'HasMod' and no accessible extension method 'HasMod' accepting a first argument of type 'ILoadOrder<IModListing<ISkyrimModGetter>>' could be found (are you missing a using directive or an assembly reference?)
Utilities\ExLoadOrderUtilities.cs(34,36): error CS1061: 'ILoadOrder<IModListing<ISkyrimModGetter>>' does not contain a definition for 'HasMod' and no accessible extension method 'HasMod' accepting a first argument of type 'ILoadOrder<IModListing<ISkyrimModGetter>>' could be found (are you missing a using directive or an assembly reference?)

Modlist: [modwat](https://modwat.ch/u/mattski123)

**Comment by Excinerus** [comment]
Updated  in [dde1a4c](https://github.com/Excinerus/AI-Overhaul-Patcher/commit/dde1a4c504e40ab9109f32d503d35503e4c8b581)
