### ISSUE TITLE
Overall Blocking Error

### ISSUE THREAD

**Issue by korodic** [Excinerus/AI-Overhaul-Patcher#22]
Synthesis error shows:

> Required mods missing from load order:
> AI Overhaul.esp

The mod is confirmed in the load order and the registry is pointing to the correct Skyrim directory. Wondering if the combination of light and regular plugin files is too much? Updating to the latest AI Overhaul had no effect.

Synthesis error log shows:

> System.IndexOutOfRangeException: Index was outside the bounds of the array.
>    at Mutagen.Bethesda.Plugins.ModKey.TryFromName(ReadOnlySpan`1 str, ModType type, ModKey& modKey, String& errorReason)
>    at Mutagen.Bethesda.Plugins.ModKey.TryFromNameAndExtension(ReadOnlySpan`1 str, ModKey& modKey, String& errorReason)
>    at Mutagen.Bethesda.Plugins.Order.ModListing.TryFromString(ReadOnlySpan`1 str, Boolean enabledMarkerProcessing, ModListing& listing)
>    at Mutagen.Bethesda.Plugins.Order.ModListing.FromString(ReadOnlySpan`1 str, Boolean enabledMarkerProcessing)
>    at Mutagen.Bethesda.Plugins.Order.DI.PluginListingsParser.Parse(Stream stream)+MoveNext()
>    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
>    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
>    at Mutagen.Bethesda.Plugins.Order.DI.PluginRawListingsReader.Read(FilePath pluginPath)
>    at Mutagen.Bethesda.Plugins.Order.DI.EnabledPluginListingsProvider.Get()
>    at Mutagen.Bethesda.Plugins.Order.DI.PluginListingsProvider.Get()
>    at Mutagen.Bethesda.Plugins.Order.DI.LoadOrderListingsProvider.Get()
>    at Mutagen.Bethesda.Plugins.Order.DI.LiveLoadOrderProvider.<>c__DisplayClass13_1.<Get>b__3(Unit _)
>    at System.Reactive.Linq.ObservableImpl.Do`1.OnNext._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Do.cs:line 38

**Comment by neochiken** [comment]
Just wanted to let you know in case you are still struggling with this that updating the synthesis ui fixed it
