### ISSUE TITLE
Blocking Error

### ISSUE THREAD

**Issue by GrandADMCorgi** [Excinerus/AI-Overhaul-Patcher#27]
I'm getting this error: Program.cs(234,110): error CS0117: 'SkyrimModHeader.HeaderFlag' does not contain a definition for 'Light'
Help on troubleshooting would be appreciated.

**Comment by ghyujkilop** [comment]
Was just about to post this, hopefully gets resolved!

**Comment by WordStormRose** [comment]
I'm also getting the same error.

**Comment by MrFastZombie** [comment]
What worked for me was setting Mutagen and Synthesis to 'Match' in the patcher's versioning settings.

**Comment by TheKanten** [comment]
The patcher is searching for "SkyrimModHeader.HeaderFlag.Light;" where it should be looking for "SkyrimModHeader.HeaderFlag.Small". ssebaa's pull request fixes this issue but it still needs to be merged into the main branch.
