### ISSUE TITLE
Patcher adding Null Reference sleeping outfits

### ISSUE THREAD

**Issue by derickso** [Excinerus/AI-Overhaul-Patcher#4]
![image](https://user-images.githubusercontent.com/6112623/115110869-52b97880-9f32-11eb-8df6-50dde2d49ac2.png)

**Comment by Excinerus** [comment]
Fields have to be nullified if later mod changes conflict with AIO/USLEEP, they were just nullified incorrectly, the field had to be set to null, not its content.

If a mod reverts a change by AIO/USLEEP resetting an outfit or an override package, the field has to be nullified using SetToNull()
