### ISSUE TITLE
Player DOFT record

### ISSUE THREAD

**Issue by JigOll** [Excinerus/AI-Overhaul-Patcher#7]
The patcher copies the Default outfit record for the player, which may interfere with character creation.
Would it be possible to add a setting to keep/set that record as empty? I have a mod that does that but the patcher overrides it.
Right now I have to empty that record manually every time.
Maybe some specific options?
- (default) AI Overhaul
- empty
- copy from last plugin in LO

**Comment by Excinerus** [comment]
i'll look into how settings work, for now i'll set it to ignore the player record

**Comment by JigOll** [comment]
Many thanks :) 🥇

**Comment by Excinerus** [comment]
Added to the settings.
